version: "3"

services:
  lensreader:
    build:
      context: "../"
      dockerfile: development/Dockerfile
    environment:
      - IS_LOCAL_ENV=true
      # Uncomment this to try the barcode reader in development
      # - READER_MODEL="SparkFun DE2120"
    hostname: lensreader
    container_name: lensreader
    volumes:
      - ../:/code
    ports:
     - 8082:8082
