version: "3"

services:
  lensreader:
    build:
      context: "../"
      dockerfile: development/Dockerfile
    environment:
      - IS_LOCAL_ENV=true
    hostname: lensreader
    container_name: lensreader
    volumes:
      - ../:/code
    ports:
     - 8081:8081
